# @name login
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "root",
    "password": "sekret"
}


### Tallenna uusi muistiinpano
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "content": "REST is easy",
    "important": true
}

### Kokeillaan tuotantoa
POST https://fullstack-2024-1.onrender.com/api/notes
Content-Type: application/json

{
    "content": "Render.com is easy",
    "important": true
}


### Tallenna uusi muistiinpano ilman userid:tä
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "REST is easy",
    "important": true
}

### Lähetetään content arvo tyhjänä
# validoinnin tulisi estää tämä
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "",
    "important": true
}


### Lähetetään content arvo liian lyhyenä
# validoinnin tulisi estää tämä
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "as",
    "important": true
}

### Lähetetään boolean arvo tyhjänä
# validoinnin tulisi estää tämä
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "hello"
}



### Lähetetään jokin rikkinäinen viesti
# Tässä esimerkissä poistin content avaimen lähetettävästä objektista
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "": "REST is easy",
    "important": true
}

### Headersit pitää olla heti osoitteen jälkeen
# ei tyhjiä rivejä välissä
POST http://localhost:3001/api/notes

Content-Type: application/json

{
    "": "REST is easy",
    "important": true
}

### Headersit pitää olla application/json
# text/plain rikkoo
POST http://localhost:3001/api/notes
Content-Type: text/plain

{
    "": "REST is easy",
    "important": true
}